### ISSUE TITLE
Samples fail to build

### ISSUE THREAD

**Issue by rcurtis** [prime31/Nez-Samples#1]
After following the instructions: Do fresh checkout of the Nez-Samples repo recursively, build Nez first, then try to build Nez-samples - I get a bunch of errors.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'Color' does not contain a definition for 'MonoGameOrange'	ProjectTemplate	\Nez\Nez-Samples\ProjectTemplate\Game1.cs	21	Active
Error		The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"\Nez\Nez-Samples\Nez.Samples\Content\Content.mgcb" /platform:DesktopGL /outputDir:"\Nez\Nez-Samples\Nez.Samples\Content\bin\DesktopGL" /intermediateDir:"\Nez-Samples\Nez.Samples\Content\obj\DesktopGL" /quiet" exited with code 2.	Nez.Samples			
Error		Processor 'TiledMapProcessor' had unexpected failure!	Nez.Samples	/Nez/Nez-Samples/Nez.Samples/Content/DestructableMap/destructable-map.tmx		
Error		Processor 'TiledMapProcessor' had unexpected failure!	Nez.Samples	/Nez/Nez-Samples/Nez.Samples/Content/NinjaAdventure/map/tilemap.tmx		
Error	CS0103	The name 'Window' does not exist in the current context	Nez.Samples	p\Nez\Nez-Samples\Nez.Samples\Game1.cs	17	Active
Error	CS0103	The name 'Window' does not exist in the current context	Nez.Samples	\Nez\Nez-Samples\Nez.Samples\Game1.cs	18	Active
Error	CS0117	'Color' does not contain a definition for 'MonoGameOrange'	Nez.Samples	\Nez\Nez-Samples\Nez.Samples\SampleHelpers\SampleScene.cs	77	Active
Error	CS0117	'Color' does not contain a definition for 'MonoGameOrange'	Nez.Samples	\Nez\Nez-Samples\Nez.Samples\Scenes\Shadows\ShadowsScene.cs	26	Active
Error	CS0103	The name 'Window' does not exist in the current context	ProjectTemplate	p\Nez\Nez-Samples\ProjectTemplate\Game1.cs	17	Active
Error	CS0103	The name 'Window' does not exist in the current context	ProjectTemplate	\Nez\Nez-Samples\ProjectTemplate\Game1.cs	18	Active`

This is on VS2015 update 2.

**Comment by prime31** [comment]
I can't seem to reproduce this following the steps from the README with VS15 update 2. Do you have a functioning MonoGame 3.5.1 install? That would be the first thing to check. Make sure MonoGame 3.5.1 is installed and that the empty DesktopGL template works for you.
