### ISSUE TITLE
Cannot apply indexing with [] to an expression of type 'DeferredLight'

### ISSUE THREAD

**Issue by leshem-amit** [prime31/Nez-Samples#14]
I'm trying to build the Nez samples project but I get two errors:

`Cannot apply indexing with [] to an expression of type 'DeferredLight'`
at:

> \Nez.Samples\Scenes\Deferred Lighting\DeferredLightingController.cs	51

and
`'DeferredLight' does not contain a definition for 'Count' and no extension method 'Count' accepting a first argument of type 'DeferredLight' could be found (are you missing a using directive or an assembly reference?)`
at:

> \Nez.Samples\Scenes\Deferred Lighting\DeferredLightingController.cs	49

looks to me that at one point DeferredLight was indexable but not anymore(?)

I'm using monogame 3.5.1, on a windows with visual studio 2015.

also,
I had multiple errors about:

> 'Scene' does not contain a definition for 'findObjectOfType'

I have the feeling that its a deprecated function so I've changed it the `findComponentOfType()`
am I correct in doing so?

thanks.

**Comment by prime31** [comment]
It sounds to me like you are mixing and matching versions of Nez.Samples and the normal Nez repo. The Nez.Samples repo adds Nez as a submodule and it will only compile against that specific version of Nez. This is easily confirmed by just doing a pull of the Nez.Samples repo following the instructions in the README and compiling. It will compile without any issue.
