### ISSUE TITLE
Content path generation fails adding new content

### ISSUE THREAD

**Issue by grumpyoldman1066** [prime31/Nez-Samples#4]
I added a new folder and texture file to Content.mcgb and followed the steps to generate the content class.

The process fails with ErrorGeneratingOutput in ContentPathGenerator.cs, ""A namespace does not directly contain members such as fields or methods" and invalidates all of the provided sample content.

I have tried it with the file in the root of the project and in /shared where you originally put it.

**Comment by grumpyoldman1066** [comment]
Update:  this happens even with a fresh reinstall of the project.

**Comment by prime31** [comment]
I cant seem to repro the error you are getting. I am seeing a totally different error. It seems that the latest Xamarin or Mono update caused T4 templates to now require specifically adding the System.Core assembly. I just pushed a change that adds it and it solved the issue for me. Let me know if it fixes it for you.

**Comment by grumpyoldman1066** [comment]
That fixed it.
