### ISSUE TITLE
1 project per sample

### ISSUE THREAD

**Issue by RUSshy** [prime31/Nez-Samples#5]
Hello

Please make one project per sample, it is impossible to understand without knowing how to use Nez wich is not what a sample is made for

**Comment by prime31** [comment]
Each individual sample has all of its files conveniently located in the Scenes/SAMPLE_NAME folder as you can see [here](https://github.com/prime31/Nez-Samples/tree/master/Nez.Samples/Scenes). There are no plans to make an individual project for each of them. It just doesnt make much sense to have that many projects for simple sample Scenes.
