### ISSUE TITLE
Not compatible with collider -> Component change in Nez

### ISSUE THREAD

**Issue by roobie** [prime31/Nez-Samples#7]
https://github.com/prime31/Nez/commit/ea8cd09c7c527caaa1ac2c6d74d43d5bfacf7a0c breaks some samples. Creating this issue to track updating the samples to be compatible with the change. I'm working on a pull request.

**Comment by prime31** [comment]
The Samples repo hasn't yet been updated to the latest Nez version with the Collider changes. The update will probably go live in a few days once everything is deemed stable on the mainline since it was a pretty major change.

**Comment by roobie** [comment]
OK, so I should wait with any work on a potential pull request?

**Comment by prime31** [comment]
Yeah. No need to do a thing. Everything will get the update real soon to the latest version of Nez.

**Comment by roobie** [comment]
All right :) Thanks for your hard work. Feel free to close this if/when suitable.
