### ISSUE TITLE
Build errors on MacOS

### ISSUE THREAD

**Issue by JelleDamen** [prime31/Nez-Samples#8]
Hi, I tried to clone the sample repo and build it myself. But for some reason I'm getting 18 errors that look like this:

`/Users/jelle/Desktop/Nez-Samples/Nez.Samples/Scenes/RigidBodies/RigidBodyScene.cs(11,11): Error CS0311: The type `Nez.CircleCollider' cannot be used as type parameter `T' in the generic type or method `Nez.Entity.addComponent<T>()'. There is no implicit reference conversion from `Nez.CircleCollider' to `Nez.Component' (CS0311) (Nez.Samples)`

When I take a look at the CircleCollider it is indeed not compatible with a Nez.Component. Did something break the sample project?

**Comment by prime31** [comment]
It looks like the Nez submodule was a commit behind. Do a submodule update and everything should then be in sync for you.

**Comment by JelleDamen** [comment]
Yes, that was it. It now builds without errors.
